import { Question, TypeResult } from './types';

// Default LINE URL fallback
export const DEFAULT_LINE_URL = "https://line.me/R/ti/p/@example_common";

// 12 Questions (3 per axis)
// NOTE: Images should be placed in public/images/questions/q{id}.png
// Questions rewritten as statements for Yes/Neither/No format.
// If Yes -> First Option Value
// If No -> Second Option Value
export const QUESTIONS: Question[] = [
  // E vs I
  {
    id: 1,
    text: "休日は友達と遊んだり、賑やかな場所へ行くのが好きだ",
    axis: "EI",
    options: [
      { text: "YES", value: "E" },
      { text: "NO", value: "I" },
    ],
    imagePath: "/images/questions/q1.png",
  },
  {
    id: 2,
    text: "初対面の人とも自分から積極的に話しかける方だ",
    axis: "EI",
    options: [
      { text: "YES", value: "E" },
      { text: "NO", value: "I" },
    ],
    imagePath: "/images/questions/q2.png",
  },
  {
    id: 3,
    text: "忙しい一週間の後は、誰かと会うことで元気をチャージしたい",
    axis: "EI",
    options: [
      { text: "YES", value: "E" },
      { text: "NO", value: "I" },
    ],
    imagePath: "/images/questions/q3.png",
  },
  // S vs N
  {
    id: 4,
    text: "新しいことを学ぶときは、背景の理論よりも具体的な事実や手順が気になる",
    axis: "SN",
    options: [
      { text: "YES", value: "S" },
      { text: "NO", value: "N" },
    ],
    imagePath: "/images/questions/q4.png",
  },
  {
    id: 5,
    text: "物事を判断するときは、直感よりもこれまでの経験や実績を重視する",
    axis: "SN",
    options: [
      { text: "YES", value: "S" },
      { text: "NO", value: "N" },
    ],
    imagePath: "/images/questions/q5.png",
  },
  {
    id: 6,
    text: "自分は想像力豊かで夢見がちなタイプというよりは、現実的で地に足がついている方だ",
    axis: "SN",
    options: [
      { text: "YES", value: "S" },
      { text: "NO", value: "N" },
    ],
    imagePath: "/images/questions/q6.png",
  },
  // T vs F
  {
    id: 7,
    text: "大事な決断をするときは、感情よりも論理的なメリット・デメリットを優先する",
    axis: "TF",
    options: [
      { text: "YES", value: "T" },
      { text: "NO", value: "F" },
    ],
    imagePath: "/images/questions/q7.png",
  },
  {
    id: 8,
    text: "友達が落ち込んでいるときは、共感するよりも解決策やアドバイスを提示したい",
    axis: "TF",
    options: [
      { text: "YES", value: "T" },
      { text: "NO", value: "F" },
    ],
    imagePath: "/images/questions/q8.png",
  },
  {
    id: 9,
    text: "「優しい・気配りができる」と言われるより、「仕事ができる・頭がいい」と言われる方が嬉しい",
    axis: "TF",
    options: [
      { text: "YES", value: "T" },
      { text: "NO", value: "F" },
    ],
    imagePath: "/images/questions/q9.png",
  },
  // J vs P
  {
    id: 10,
    text: "机の上や部屋はいつも整理整頓されている方だ",
    axis: "JP",
    options: [
      { text: "YES", value: "J" },
      { text: "NO", value: "P" },
    ],
    imagePath: "/images/questions/q10.png",
  },
  {
    id: 11,
    text: "旅行の計画は現地での気分任せにせず、しっかりとスケジュールを立てたい",
    axis: "JP",
    options: [
      { text: "YES", value: "J" },
      { text: "NO", value: "P" },
    ],
    imagePath: "/images/questions/q11.png",
  },
  {
    id: 12,
    text: "締め切りや約束に対しては、ギリギリではなく余裕を持って終わらせたい",
    axis: "JP",
    options: [
      { text: "YES", value: "J" },
      { text: "NO", value: "P" },
    ],
    imagePath: "/images/questions/q12.png",
  },
];

// Result Data
// NOTE: Images should be placed in public/images/results/{type}.png
export const RESULTS: Record<string, TypeResult> = {
  ISTJ: {
    type: "ISTJ",
    title: "管理者タイプ",
    description: "真面目で責任感が強く、コツコツと物事を進めるしっかり者。",
    strengths: ["誠実で嘘をつかない", "責任感が強い", "計画的"],
    strengthIntro: "一貫した誠実さと強い責任感を持っており、どんな状況でも約束を守り抜く姿勢が周囲から深く信頼されています",
    weaknesses: ["頑固になりがち", "変化が苦手", "理屈っぽくなることも"],
    weaknessIntro: "慣れ親しんだ方法や安定を好みすぎるあまり、急な予定変更や新しいやり方に対して柔軟に対応するのが少し苦手です",
    professions: ["公務員", "会計士", "システム管理者", "法曹界"],
    lineUrl: "https://line.me/R/ti/p/@istj_link",
    imagePath: "/images/results/ISTJ.png",
  },
  ISFJ: {
    type: "ISFJ",
    title: "擁護者タイプ",
    description: "思いやりがあり、大切な人を守るために尽くす献身的なサポーター。",
    strengths: ["協調性がある", "細かい気配りができる", "忍耐強い"],
    strengthIntro: "相手の気持ちに寄り添った細やかな気配りが自然とでき、困っている人を放っておけない献身的な優しさを持っています",
    weaknesses: ["断るのが苦手", "自分を後回しにしがち", "変化にストレスを感じる"],
    weaknessIntro: "他人の頼み事を断るのが苦手で、つい無理をして自分のことを後回しにしてしまい、ストレスを溜め込む傾向があります",
    professions: ["看護師", "教師", "人事・総務", "カウンセラー"],
    lineUrl: "https://line.me/R/ti/p/@isfj_link",
    imagePath: "/images/results/ISFJ.png",
  },
  INFJ: {
    type: "INFJ",
    title: "提唱者タイプ",
    description: "静かながらも熱い理想を持ち、人々の心を動かす不思議な魅力の持ち主。",
    strengths: ["洞察力が鋭い", "創造的", "信念が強い"],
    strengthIntro: "物事の表面だけでなく本質を見抜く鋭い洞察力を持ち、独自の理想と信念を掲げて人々を導く静かな強さがあります",
    weaknesses: ["繊細で傷つきやすい", "理想が高すぎる", "燃え尽きやすい"],
    weaknessIntro: "理想を追い求めるあまり、現実とのギャップに悩みやすく、周囲の感情に敏感すぎて精神的に疲れ果ててしまうことがあります",
    professions: ["心理カウンセラー", "作家・ライター", "非営利団体職員", "デザイナー"],
    lineUrl: "https://line.me/R/ti/p/@infj_link",
    imagePath: "/images/results/INFJ.png",
  },
  INTJ: {
    type: "INTJ",
    title: "建築家タイプ",
    description: "豊かな想像力と戦略的思考を持ち、あらゆることの計画を立てる完璧主義者。",
    strengths: ["論理的思考力", "高い向上心", "独創的なアイデア"],
    strengthIntro: "独創的な視点と論理的な思考を組み合わせ、誰も思いつかないような戦略で困難な目標も着実に達成へと導きます",
    weaknesses: ["理屈っぽすぎる", "批判的になりがち", "感情表現が苦手"],
    weaknessIntro: "論理的な正しさを優先しすぎて、相手の感情や場の空気を読み取るのが疎かになり、冷たい印象を与えてしまうことがあります",
    professions: ["経営コンサルタント", "ソフトウェア開発者", "科学者", "投資銀行家"],
    lineUrl: "https://line.me/R/ti/p/@intj_link",
    imagePath: "/images/results/INTJ.png",
  },
  ISTP: {
    type: "ISTP",
    title: "巨匠タイプ",
    description: "好奇心旺盛で、自分の手で触れて学ぶことが大好きなクールな職人肌。",
    strengths: ["冷静沈着", "手先が器用", "柔軟な対応力"],
    strengthIntro: "どんなトラブルが起きても動じない冷静さと、状況に合わせて即座に対応できる柔軟性を持ち合わせています",
    weaknesses: ["飽きっぽい", "リスクを冒しがち", "感情を表に出さない"],
    weaknessIntro: "興味の対象が次々と変わるため一つのことが長続きせず、刺激を求めてリスクの高い行動をとってしまうことがあります",
    professions: ["エンジニア", "パイロット", "救急救命士", "データアナリスト"],
    lineUrl: "https://line.me/R/ti/p/@istp_link",
    imagePath: "/images/results/ISTP.png",
  },
  ISFP: {
    type: "ISFP",
    title: "冒険家タイプ",
    description: "感性豊かで芸術的。型にはまらず、新しい体験を楽しむ自由人。",
    strengths: ["芸術的センス", "優しい", "今この瞬間を楽しめる"],
    strengthIntro: "豊かな感性と独自の美的センスを持ち、日々の何気ない瞬間にも喜びや美しさを見つけることができる芸術家肌です",
    weaknesses: ["計画性がない", "ストレスに弱い", "競争が苦手"],
    weaknessIntro: "争いごとや競争を極端に避けるため、自分の意見を主張するのが苦手で、長期的な計画を立てるのもあまり得意ではありません",
    professions: ["アーティスト", "ファッションデザイナー", "理学療法士", "フローリスト"],
    lineUrl: "https://line.me/R/ti/p/@isfp_link",
    imagePath: "/images/results/ISFP.png",
  },
  INFP: {
    type: "INFP",
    title: "仲介者タイプ",
    description: "詩的で親切。いつも良いことのためにお手伝いしたいと願う、夢見る理想主義者。",
    strengths: ["共感力が高い", "クリエイティブ", "心が広い"],
    strengthIntro: "他者の痛みを自分のことのように感じる深い優しさと、豊かな想像力を活かして、人々の心を癒す不思議な力を持っています",
    weaknesses: ["現実離れしがち", "傷つきやすい", "決断が苦手"],
    weaknessIntro: "繊細な感受性ゆえに、些細な言葉にも深く傷ついてしまったり、現実的な問題への対処を後回しにしてしまうことがあります",
    professions: ["編集者", "心理学者", "ソーシャルワーカー", "通訳・翻訳者"],
    lineUrl: "https://line.me/R/ti/p/@infp_link",
    imagePath: "/images/results/INFP.png",
  },
  INTP: {
    type: "INTP",
    title: "論理学者タイプ",
    description: "貪欲な知識欲を持つ革新的な発明家。頭の中は常に新しいアイデアでいっぱい。",
    strengths: ["分析力が高い", "独創的", "偏見を持たない"],
    strengthIntro: "尽きることのない知的好奇心と鋭い分析力で、常識にとらわれず物事の本質や仕組みを深く理解しようとします",
    weaknesses: ["考えすぎる", "感情に疎い", "ルーチンワークが苦手"],
    weaknessIntro: "頭の中でのシミュレーションに時間をかけすぎて行動が遅れたり、他人の感情的な機微を理解するのが苦手な一面があります",
    professions: ["プログラマー", "研究者", "数学者", "システムアナリスト"],
    lineUrl: "https://line.me/R/ti/p/@intp_link",
    imagePath: "/images/results/INTP.png",
  },
  ESTP: {
    type: "ESTP",
    title: "起業家タイプ",
    description: "賢くてエネルギッシュ。危険と隣り合わせの生活を心から楽しむ人。",
    strengths: ["行動力がある", "現実的", "社交的で目立つ"],
    strengthIntro: "考えるよりもまず行動する抜群のフットワークを持ち、持ち前の明るさと行動力で周囲を巻き込みながら道を切り拓きます",
    weaknesses: ["せっかち", "リスクを恐れない", "計画性がない"],
    weaknessIntro: "思い立ったら即行動する反面、長期的なリスクや結果を深く考えずに勢いだけで動いてしまい、失敗することがあります",
    professions: ["セールスマン", "起業家", "スポーツ選手", "警察官・消防士"],
    lineUrl: "https://line.me/R/ti/p/@estp_link",
    imagePath: "/images/results/ESTP.png",
  },
  ESFP: {
    type: "ESFP",
    title: "エンターテイナータイプ",
    description: "自発的でエネルギッシュ。周りの人を巻き込んで楽しませる天才。",
    strengths: ["明るくポジティブ", "美的センスがある", "人を楽しませる"],
    strengthIntro: "天性の明るさとサービス精神で、どこに行ってもその場の雰囲気を一瞬で明るくし、周りの人々を笑顔にする才能があります",
    weaknesses: ["集中力が続かない", "計画性がない", "批判に弱い"],
    weaknessIntro: "楽しいことを優先しすぎてやるべきことを後回しにしがちで、少しでも批判されると過剰に落ち込んでしまうことがあります",
    professions: ["イベントプランナー", "接客業", "タレント・俳優", "ツアーガイド"],
    lineUrl: "https://line.me/R/ti/p/@esfp_link",
    imagePath: "/images/results/ESFP.png",
  },
  ENFP: {
    type: "ENFP",
    title: "広報運動家タイプ",
    description: "情熱的で独創的。かつ社交的な自由人。常に笑いかける理由を見つけられる。",
    strengths: ["好奇心旺盛", "コミュニケーション能力が高い", "エネルギッシュ"],
    strengthIntro: "自由な発想と溢れる情熱で新しい可能性を次々と見つけ出し、そのワクワクを周りの人に伝染させるエネルギーを持っています",
    weaknesses: ["集中力が散漫", "考えすぎる", "ストレスを溜めやすい"],
    weaknessIntro: "興味の対象が目まぐるしく変わるため一つのことが続かず、細かい事務作業やルーチンワークに対して強いストレスを感じます",
    professions: ["ジャーナリスト", "広告代理店", "イベントプロデューサー", "教師"],
    lineUrl: "https://line.me/R/ti/p/@enfp_link",
    imagePath: "/images/results/ENFP.png",
  },
  ENTP: {
    type: "ENTP",
    title: "討論者タイプ",
    description: "賢くて好奇心旺盛な思考家。知的な挑戦には必ず受けて立つ。",
    strengths: ["知識豊富", "頭の回転が速い", "カリスマ性がある"],
    strengthIntro: "頭の回転が非常に速く、誰も思いつかないような独創的なアイデアや解決策を提示して、周囲を驚かせる知性を持っています",
    weaknesses: ["議論好きすぎる", "飽きっぽい", "細かい作業が苦手"],
    weaknessIntro: "議論に勝つことにこだわりすぎて敵を作ってしまったり、アイデアを出すだけで実行や詳細な詰めを人任せにしがちです",
    professions: ["弁護士", "マーケティング職", "政治家", "コンサルタント"],
    lineUrl: "https://line.me/R/ti/p/@entp_link",
    imagePath: "/images/results/ENTP.png",
  },
  ESTJ: {
    type: "ESTJ",
    title: "幹部タイプ",
    description: "優秀な管理者。物事や人々を管理する能力にかけては右に出る者はいない。",
    strengths: ["リーダーシップがある", "組織的", "意志が強い"],
    strengthIntro: "明確なルールと秩序を重んじ、優れた指導力と決断力で組織をまとめあげ、目標達成へと確実に導くリーダーです",
    weaknesses: ["柔軟性に欠ける", "頑固", "感情論が通じない"],
    weaknessIntro: "自分のやり方やルールにこだわりすぎるあまり、他人の意見や新しい方法を受け入れる柔軟性に欠けることがあります",
    professions: ["プロジェクトマネージャー", "裁判官", "銀行員", "軍人・警察官"],
    lineUrl: "https://line.me/R/ti/p/@estj_link",
    imagePath: "/images/results/ESTJ.png",
  },
  ESFJ: {
    type: "ESFJ",
    title: "領事官タイプ",
    description: "非常に思いやりがあり社交的。いつも誰かの助けになりたいと考えている。",
    strengths: ["面倒見が良い", "義理堅い", "ムードメーカー"],
    strengthIntro: "人との繋がりを何よりも大切にし、細やかな気配りと温かい笑顔で、周囲に安心感と調和をもたらすムードメーカーです",
    weaknesses: ["批判に弱い", "変化を嫌う", "お節介になりがち"],
    weaknessIntro: "周りの目や評価を気にしすぎて自分の意見を言えなかったり、良かれと思ってしたことがお節介になってしまうことがあります",
    professions: ["保育士", "医療事務", "広報・PR", "カウンセラー"],
    lineUrl: "https://line.me/R/ti/p/@esfj_link",
    imagePath: "/images/results/ESFJ.png",
  },
  ENFJ: {
    type: "ENFJ",
    title: "主人公タイプ",
    description: "カリスマ性があり、人々を励ますリーダー。聞く人を魅了する。",
    strengths: ["人を惹きつける", "信頼できる", "情熱的"],
    strengthIntro: "人々を励まし、やる気を引き出す天性のカリスマ性を持ち、みんなが幸せになれるようなより良い未来へと導くリーダーです",
    weaknesses: ["理想が高すぎる", "繊細すぎる", "自己犠牲的になりがち"],
    weaknessIntro: "他人の問題を自分のことのように背負いすぎてしまったり、全員に好かれようとして無理を重ね、自分自身が疲弊しがちです",
    professions: ["教師・講師", "人事マネージャー", "政治活動家", "セールスマネージャー"],
    lineUrl: "https://line.me/R/ti/p/@enfj_link",
    imagePath: "/images/results/ENFJ.png",
  },
  ENTJ: {
    type: "ENTJ",
    title: "指揮官タイプ",
    description: "大胆で想像力豊か、かつ強い意志を持つ指導者。道を見つけるか、作り出す。",
    strengths: ["効率的", "自信に満ちている", "決断力がある"],
    strengthIntro: "揺るぎない自信と強い意志を持ち、非効率なことを見逃さず、どんな困難な状況でも論理的に解決し目標を達成させます",
    weaknesses: ["高圧的になりがち", "傲慢に見える", "感情を軽視する"],
    weaknessIntro: "目標達成や効率を優先するあまり、周りの人の感情やペースを無視してしまい、冷酷で高圧的な印象を与えてしまうことがあります",
    professions: ["経営者・CEO", "投資家", "大学教授", "弁護士"],
    lineUrl: "https://line.me/R/ti/p/@entj_link",
    imagePath: "/images/results/ENTJ.png",
  },
};